// Wire-protocol contract test.
//
// The strings below are the channel protocol shared by three codebases
// (Dart, Kotlin, Swift). If any assertion here fails, a refactor changed the
// wire protocol — either revert the Dart change or update Kotlin AND Swift
// (and this file) together in one commit.

import 'package:flutter_test/flutter_test.dart';
import 'package:pjsip_connect_flutter/src/pjsip_connect_platform.dart';

void main() {
  test('channel name is stable', () {
    expect(PjsipConnectPlatform.kChannelName, 'sip_connect_flutter');
  });

  test('Dart->native method names are stable', () {
    const expected = <String, String>{
      'kMethodModuleInitialize': 'Module_Initialize',
      'kMethodModuleUnInitialize': 'Module_UnInitialize',
      'kMethodModuleHomeFolder': 'Module_HomeFolder',
      'kMethodModuleVersionCode': 'Module_VersionCode',
      'kMethodModuleVersion': 'Module_Version',
      'kMethodAccountAdd': 'Account_Add',
      'kMethodAccountUpdate': 'Account_Update',
      'kMethodAccountRegister': 'Account_Register',
      'kMethodAccountUnregister': 'Account_Unregister',
      'kMethodAccountDelete': 'Account_Delete',
      'kMethodAccountGenInstId': 'Account_GenInstId',
      'kMethodCallInvite': 'Call_Invite',
      'kMethodCallReject': 'Call_Reject',
      'kMethodCallAccept': 'Call_Accept',
      'kMethodCallHold': 'Call_Hold',
      'kMethodCallGetHoldState': 'Call_GetHoldState',
      'kMethodCallGetSipHeader': 'Call_GetSipHeader',
      'kMethodCallGetStats': 'Call_GetStats',
      'kMethodCallMuteMic': 'Call_MuteMic',
      'kMethodCallMuteCam': 'Call_MuteCam',
      'kMethodCallSendDtmf': 'Call_SendDtmf',
      'kMethodCallPlayFile': 'Call_PlayFile',
      'kMethodCallPlayTone': 'Call_PlayTone',
      'kMethodCallStopPlayFile': 'Call_StopPlayFile',
      'kMethodCallRecordFile': 'Call_RecordFile',
      'kMethodCallStopRecordFile': 'Call_StopRecordFile',
      'kMethodCallTransferBlind': 'Call_TransferBlind',
      'kMethodCallTransferAttended': 'Call_TransferAttended',
      'kMethodCallStopRingtone': 'Call_StopRingtone',
      'kMethodCallUpgradeToVideo': 'Call_UpgradeToVideo',
      'kMethodCallAcceptVideoUpgrade': 'Call_AcceptVideoUpgrade',
      'kMethodCallBye': 'Call_Bye',
      'kMethodMixerSwitchToCall': 'Mixer_SwitchToCall',
      'kMethodMixerMakeConference': 'Mixer_MakeConference',
      'kMethodMessageSend': 'Message_Send',
      'kMethodSubscriptionAdd': 'Subscription_Add',
      'kMethodSubscriptionDelete': 'Subscription_Delete',
      'kMethodDvcGetPushKitToken': 'Dvc_GetPushKitToken',
      'kMethodDvcUpdCallKitDetails': 'Dvc_UpdCallKitDetails',
      'kMethodDvcGetCallKitUUID': 'Dvc_GetCallKitUUID',
      'kMethodDvcEndCallKitCall': 'Dvc_EndCallKitCall',
      'kMethodDvcSetForegroundMode': 'Dvc_SetForegroundMode',
      'kMethodDvcIsForegroundMode': 'Dvc_IsForegroundMode',
      'kMethodDvcSyncCallsState': 'Dvc_SyncCallsState',
      'kMethodDvcGetPlayoutNumber': 'Dvc_GetPlayoutDevices',
      'kMethodDvcGetRecordNumber': 'Dvc_GetRecordingDevices',
      'kMethodDvcGetVideoNumber': 'Dvc_GetVideoDevices',
      'kMethodDvcGetPlayout': 'Dvc_GetPlayoutDevice',
      'kMethodDvcGetRecording': 'Dvc_GetRecordingDevice',
      'kMethodDvcGetVideo': 'Dvc_GetVideoDevice',
      'kMethodDvcSetPlayout': 'Dvc_SetPlayoutDevice',
      'kMethodDvcSetRecording': 'Dvc_SetRecordingDevice',
      'kMethodDvcSetVideo': 'Dvc_SetVideoDevice',
      'kMethodDvcSetVideoParams': 'Dvc_SetVideoParams',
      'kMethodDvcSwitchCamera': 'Dvc_SwitchCamera',
      'kMethodVideoRendererCreate': 'Video_RendererCreate',
      'kMethodVideoRendererSetSrc': 'Video_RendererSetSrc',
      'kMethodVideoRendererDispose': 'Video_RendererDispose',
    };

    final actual = <String, String>{
      'kMethodModuleInitialize': PjsipConnectPlatform.kMethodModuleInitialize,
      'kMethodModuleUnInitialize': PjsipConnectPlatform.kMethodModuleUnInitialize,
      'kMethodModuleHomeFolder': PjsipConnectPlatform.kMethodModuleHomeFolder,
      'kMethodModuleVersionCode': PjsipConnectPlatform.kMethodModuleVersionCode,
      'kMethodModuleVersion': PjsipConnectPlatform.kMethodModuleVersion,
      'kMethodAccountAdd': PjsipConnectPlatform.kMethodAccountAdd,
      'kMethodAccountUpdate': PjsipConnectPlatform.kMethodAccountUpdate,
      'kMethodAccountRegister': PjsipConnectPlatform.kMethodAccountRegister,
      'kMethodAccountUnregister': PjsipConnectPlatform.kMethodAccountUnregister,
      'kMethodAccountDelete': PjsipConnectPlatform.kMethodAccountDelete,
      'kMethodAccountGenInstId': PjsipConnectPlatform.kMethodAccountGenInstId,
      'kMethodCallInvite': PjsipConnectPlatform.kMethodCallInvite,
      'kMethodCallReject': PjsipConnectPlatform.kMethodCallReject,
      'kMethodCallAccept': PjsipConnectPlatform.kMethodCallAccept,
      'kMethodCallHold': PjsipConnectPlatform.kMethodCallHold,
      'kMethodCallGetHoldState': PjsipConnectPlatform.kMethodCallGetHoldState,
      'kMethodCallGetSipHeader': PjsipConnectPlatform.kMethodCallGetSipHeader,
      'kMethodCallGetStats': PjsipConnectPlatform.kMethodCallGetStats,
      'kMethodCallMuteMic': PjsipConnectPlatform.kMethodCallMuteMic,
      'kMethodCallMuteCam': PjsipConnectPlatform.kMethodCallMuteCam,
      'kMethodCallSendDtmf': PjsipConnectPlatform.kMethodCallSendDtmf,
      'kMethodCallPlayFile': PjsipConnectPlatform.kMethodCallPlayFile,
      'kMethodCallPlayTone': PjsipConnectPlatform.kMethodCallPlayTone,
      'kMethodCallStopPlayFile': PjsipConnectPlatform.kMethodCallStopPlayFile,
      'kMethodCallRecordFile': PjsipConnectPlatform.kMethodCallRecordFile,
      'kMethodCallStopRecordFile': PjsipConnectPlatform.kMethodCallStopRecordFile,
      'kMethodCallTransferBlind': PjsipConnectPlatform.kMethodCallTransferBlind,
      'kMethodCallTransferAttended': PjsipConnectPlatform.kMethodCallTransferAttended,
      'kMethodCallStopRingtone': PjsipConnectPlatform.kMethodCallStopRingtone,
      'kMethodCallUpgradeToVideo': PjsipConnectPlatform.kMethodCallUpgradeToVideo,
      'kMethodCallAcceptVideoUpgrade': PjsipConnectPlatform.kMethodCallAcceptVideoUpgrade,
      'kMethodCallBye': PjsipConnectPlatform.kMethodCallBye,
      'kMethodMixerSwitchToCall': PjsipConnectPlatform.kMethodMixerSwitchToCall,
      'kMethodMixerMakeConference': PjsipConnectPlatform.kMethodMixerMakeConference,
      'kMethodMessageSend': PjsipConnectPlatform.kMethodMessageSend,
      'kMethodSubscriptionAdd': PjsipConnectPlatform.kMethodSubscriptionAdd,
      'kMethodSubscriptionDelete': PjsipConnectPlatform.kMethodSubscriptionDelete,
      'kMethodDvcGetPushKitToken': PjsipConnectPlatform.kMethodDvcGetPushKitToken,
      'kMethodDvcUpdCallKitDetails': PjsipConnectPlatform.kMethodDvcUpdCallKitDetails,
      'kMethodDvcGetCallKitUUID': PjsipConnectPlatform.kMethodDvcGetCallKitUUID,
      'kMethodDvcEndCallKitCall': PjsipConnectPlatform.kMethodDvcEndCallKitCall,
      'kMethodDvcSetForegroundMode': PjsipConnectPlatform.kMethodDvcSetForegroundMode,
      'kMethodDvcIsForegroundMode': PjsipConnectPlatform.kMethodDvcIsForegroundMode,
      'kMethodDvcSyncCallsState': PjsipConnectPlatform.kMethodDvcSyncCallsState,
      'kMethodDvcGetPlayoutNumber': PjsipConnectPlatform.kMethodDvcGetPlayoutNumber,
      'kMethodDvcGetRecordNumber': PjsipConnectPlatform.kMethodDvcGetRecordNumber,
      'kMethodDvcGetVideoNumber': PjsipConnectPlatform.kMethodDvcGetVideoNumber,
      'kMethodDvcGetPlayout': PjsipConnectPlatform.kMethodDvcGetPlayout,
      'kMethodDvcGetRecording': PjsipConnectPlatform.kMethodDvcGetRecording,
      'kMethodDvcGetVideo': PjsipConnectPlatform.kMethodDvcGetVideo,
      'kMethodDvcSetPlayout': PjsipConnectPlatform.kMethodDvcSetPlayout,
      'kMethodDvcSetRecording': PjsipConnectPlatform.kMethodDvcSetRecording,
      'kMethodDvcSetVideo': PjsipConnectPlatform.kMethodDvcSetVideo,
      'kMethodDvcSetVideoParams': PjsipConnectPlatform.kMethodDvcSetVideoParams,
      'kMethodDvcSwitchCamera': PjsipConnectPlatform.kMethodDvcSwitchCamera,
      'kMethodVideoRendererCreate': PjsipConnectPlatform.kMethodVideoRendererCreate,
      'kMethodVideoRendererSetSrc': PjsipConnectPlatform.kMethodVideoRendererSetSrc,
      'kMethodVideoRendererDispose': PjsipConnectPlatform.kMethodVideoRendererDispose,
    };
    expect(actual, expected);
  });

  test('native->Dart event names are stable', () {
    const expected = <String, String>{
      'kOnPushIncoming': 'OnPushIncoming',
      'kOnTrialModeNotif': 'OnTrialModeNotif',
      'kOnDevicesChanged': 'OnDevicesChanged',
      'kOnAccountRegState': 'OnAccountRegState',
      'kOnSubscriptionState': 'OnSubscriptionState',
      'kOnNetworkState': 'OnNetworkState',
      'kOnPlayerState': 'OnPlayerState',
      'kOnCallProceeding': 'OnCallProceeding',
      'kOnCallTerminated': 'OnCallTerminated',
      'kOnCallConnected': 'OnCallConnected',
      'kOnCallIncoming': 'OnCallIncoming',
      'kOnCallAcceptNotif': 'OnCallAcceptNotif',
      'kOnCallDtmfReceived': 'OnCallDtmfReceived',
      'kOnCallTransferred': 'OnCallTransferred',
      'kOnCallRedirected': 'OnCallRedirected',
      'kOnCallVideoUpgraded': 'OnCallVideoUpgraded',
      'kOnCallVideoUpgradeRequested': 'OnCallVideoUpgradeRequested',
      'kOnCallSwitched': 'OnCallSwitched',
      'kOnCallHeld': 'OnCallHeld',
      'kOnCallKitMuted': 'OnCallKitMuted',
      'kOnCallsSyncState': 'OnCallsSyncState',
      'kOnMessageSentState': 'OnMessageSentState',
      'kOnMessageIncoming': 'OnMessageIncoming',
      'kOnSipNotify': 'OnSipNotify',
      'kOnVuMeterLevel': 'OnVuMeterLevel',
    };
    final actual = <String, String>{
      'kOnPushIncoming': PjsipConnectPlatform.kOnPushIncoming,
      'kOnTrialModeNotif': PjsipConnectPlatform.kOnTrialModeNotif,
      'kOnDevicesChanged': PjsipConnectPlatform.kOnDevicesChanged,
      'kOnAccountRegState': PjsipConnectPlatform.kOnAccountRegState,
      'kOnSubscriptionState': PjsipConnectPlatform.kOnSubscriptionState,
      'kOnNetworkState': PjsipConnectPlatform.kOnNetworkState,
      'kOnPlayerState': PjsipConnectPlatform.kOnPlayerState,
      'kOnCallProceeding': PjsipConnectPlatform.kOnCallProceeding,
      'kOnCallTerminated': PjsipConnectPlatform.kOnCallTerminated,
      'kOnCallConnected': PjsipConnectPlatform.kOnCallConnected,
      'kOnCallIncoming': PjsipConnectPlatform.kOnCallIncoming,
      'kOnCallAcceptNotif': PjsipConnectPlatform.kOnCallAcceptNotif,
      'kOnCallDtmfReceived': PjsipConnectPlatform.kOnCallDtmfReceived,
      'kOnCallTransferred': PjsipConnectPlatform.kOnCallTransferred,
      'kOnCallRedirected': PjsipConnectPlatform.kOnCallRedirected,
      'kOnCallVideoUpgraded': PjsipConnectPlatform.kOnCallVideoUpgraded,
      'kOnCallVideoUpgradeRequested': PjsipConnectPlatform.kOnCallVideoUpgradeRequested,
      'kOnCallSwitched': PjsipConnectPlatform.kOnCallSwitched,
      'kOnCallHeld': PjsipConnectPlatform.kOnCallHeld,
      'kOnCallKitMuted': PjsipConnectPlatform.kOnCallKitMuted,
      'kOnCallsSyncState': PjsipConnectPlatform.kOnCallsSyncState,
      'kOnMessageSentState': PjsipConnectPlatform.kOnMessageSentState,
      'kOnMessageIncoming': PjsipConnectPlatform.kOnMessageIncoming,
      'kOnSipNotify': PjsipConnectPlatform.kOnSipNotify,
      'kOnVuMeterLevel': PjsipConnectPlatform.kOnVuMeterLevel,
    };
    expect(actual, expected);
  });
}
