// swift-tools-version: 5.9
// Swift Package Manager manifest for the sip_connect_flutter iOS plugin.
//
// Two targets because SPM (unlike CocoaPods) forbids mixing Swift and
// Objective-C++ in one target:
//   - SipCoreModule: ObjC++ bridge over the vendored PJSIP static libs
//     (pjsip.xcframework, headers in ../pjsip-headers). Public API is
//     include/SipCoreModule.h — pure ObjC, safe for Swift import.
//   - sip_connect_flutter: the Swift plugin classes (Flutter channel,
//     CallKit/PushKit providers), importing SipCoreModule as a module.
// The CocoaPods build (sip_connect_flutter.podspec) compiles the same files
// from this directory as a single mixed pod.

import PackageDescription

let package = Package(
    name: "sip_connect_flutter",
    platforms: [
        .iOS("14.0")
    ],
    products: [
        .library(name: "sip-connect-flutter", targets: ["sip_connect_flutter"])
    ],
    dependencies: [
        // Ephemeral package generated by the Flutter tool next to this one
        // at build time; provides the Flutter.xcframework module.
        .package(name: "FlutterFramework", path: "../FlutterFramework")
    ],
    targets: [
        .binaryTarget(
            name: "pjsip",
            path: "pjsip.xcframework"
        ),
        .target(
            name: "SipCoreModule",
            dependencies: ["pjsip"],
            cxxSettings: [
                .headerSearchPath("../../pjsip-headers"),
                .define("PJ_AUTOCONF", to: "1")
            ],
            linkerSettings: [
                .linkedLibrary("c++"),
                .linkedLibrary("resolv"),
                .linkedFramework("AVFoundation"),
                .linkedFramework("AudioToolbox"),
                .linkedFramework("CoreAudio"),
                .linkedFramework("CoreMedia"),
                .linkedFramework("CoreVideo"),
                .linkedFramework("VideoToolbox"),
                .linkedFramework("CFNetwork"),
                .linkedFramework("UIKit"),
                .linkedFramework("Network"),
                .linkedFramework("Metal"),
                .linkedFramework("MetalKit")
            ]
        ),
        .target(
            name: "sip_connect_flutter",
            dependencies: [
                "SipCoreModule",
                .product(name: "FlutterFramework", package: "FlutterFramework")
            ]
        )
    ],
    cxxLanguageStandard: .cxx17
)
